refac(actions): updated dotnet version and added linter

diff --git a/.github/workflows/build-test-lint.yml b/.github/workflows/build-test-lint.yml
--- a/.github/workflows/build-test-lint.yml
+++ b/.github/workflows/build-test-lint.yml
@@ -5,28 +5,26 @@ on:
     branches: [master, develop]
     types: [opened, reopened, synchronize]
 
+permissions:
+  contents: read
+  pull-requests: read
+
 jobs:
-  build:
+  build-and-test:
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      pull-requests: read
     env:
       SOLUTION_FILE: ./src/ItemsShop.sln
       PROJECT_PATH: ./src/Host/ItemsShop.Host/ItemsShop.Host.csproj
-
     steps:
       - uses: actions/checkout@v6
-        with:
-          persist-credentials: false
-
       - name: Setup dotnet
         uses: actions/setup-dotnet@v5
         with:
-          dotnet-version: 9.0.*
+          dotnet-version: 10.0.*
 
       - name: Install dependencies
-        run: dotnet restore ${{ env.SOLUTION_FILE }}
+        run: |
+          dotnet restore ${{ env.SOLUTION_FILE }} --disable-parallel
 
       - name: Build
         run: |
@@ -41,3 +39,21 @@ jobs:
             --no-build \
             --no-restore \
             --verbosity normal
+
+  lint-only:
+    runs-on: ubuntu-latest
+    if: github.event_name == 'pull_request'
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v6
+      - name: Setup dotnet
+        uses: actions/setup-dotnet@v5
+        with:
+          dotnet-version: 10.0.*
+      - name: Install dotnet-format
+        run: |
+          dotnet tool install -g dotnet-format || true
+          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
+      - name: dotnet format (check only)
+        run: |
+          dotnet format --verify-no-changes || (echo "Formatting errors found" && exit 1)
